version: '3.8'
name: chat
services:
  postgres-main:
    container_name: main-chat
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=db-chat
